# Домашнее задание 5

Перед выполнением заданий необходимо сохранить копию этого блокнота себе на диск. Или скачать `.ipynb`/`.py` файл для локальной разработки.

За работу можно получить максимум 8 баллов.

## Полным полна коробочка (1 балл)


Создайте список, содержащий: вектор, матрицу и подсписок.
Обратитесь к элементам списка разными способами ($, [[ ]], [ ]).
Измените один элемент в подсписке.

In [ ]:
my_list <- list(
  vector = c(1, 2, 3, 4),
  matrix = matrix(1:6, nrow = 2, ncol = 3),
  sublist = list(a = 10, b = 20, c = 30)
)
print(my_list)

print(my_list$vector)
print(my_list$sublist$a)

print(my_list[["matrix"]])
print(my_list[["sublist"]][["b"]])

print(my_list["vector"])
print(my_list["sublist"])

my_list$sublist$c <- 100

print(my_list$sublist)

$vector
[1] 1 2 3 4

$matrix
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

$sublist
$sublist$a
[1] 10

$sublist$b
[1] 20

$sublist$c
[1] 30


[1] 1 2 3 4
[1] 10
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
[1] 20
$vector
[1] 1 2 3 4

$sublist
$sublist$a
[1] 10

$sublist$b
[1] 20

$sublist$c
[1] 30


$a
[1] 10

$b
[1] 20

$c
[1] 100



## Матрицы атакуют (1 балл)

Найти решение системы

$$
\begin{equation}
\begin{cases}
\xi_1 & + & 2 \xi_2 & + & 3 \xi_3 & + & 4 \xi_4 & + & 5 \xi_5 & = & 2
\\
2\xi_1 & + & 3 \xi_2 & + & 7 \xi_3 & + & 10 \xi_4 & + & 13 \xi_5 & = & 12
\\
3\xi_1 & + & 5 \xi_2 & + & 11 \xi_3 & + & 16 \xi_4 & + & 21 \xi_5 & = & 17
\\
2\xi_1 & - & 7 \xi_2 & + & 7 \xi_3 & + & 7 \xi_4 & + & 2 \xi_5 & = & 57
\\
\xi_1 & + & 4 \xi_2 & + & 5 \xi_3 & + & 3 \xi_4 & + & 10 \xi_5 & = & 7
\end{cases}
\end{equation}
$$

PS: используйте встроенные в R функции решения систем.

In [ ]:
A <- matrix(c(
  1, 2, 3, 4, 5,
  2, 3, 7, 10, 13,
  3, 5, 11, 16, 21,
  2, -7, 7, 7, 2,
  1, 4, 5, 3, 10
), nrow = 5, byrow = TRUE)

b <- c(2, 12, 17, 57, 7)

solution <- solve(A, b)

cat("Решение системы:\n")
print(solution)

Решение системы:
[1]  3 -5  4 -2  1


## Снова матрицы (1 балл)

Создайте матрицу 5 на 5, заполнив ее произвольными числами.

* выведите элемент из третей строки и четвертого столбца
* замените значения второго столбца на ваш номер ИСУ без первой цифры
* вычислить сумму значений по каждой строке и каюдому столбцу

Рекомендуем для проверки выводить в консоль промежуточные значения матрицы.

In [ ]:
set.seed(42)
mat <- matrix(sample(1:50, 25, replace = TRUE), nrow = 5, ncol = 5)

cat("Исходная матрица:\n")
print(mat)

element_3_4 <- mat[3, 4]
cat("\nЭлемент [3,4] =", element_3_4, "\n")

isu_tail <- c(0, 2, 7, 5, 7)

mat[, 2] <- isu_tail

cat("\nМатрица после замены 2-го столбца на 0,2,7,5,7:\n")
print(mat)

row_sums <- rowSums(mat)
col_sums <- colSums(mat)

cat("\nСуммы по строкам:\n")
print(row_sums)

cat("\nСуммы по столбцам:\n")
print(col_sums)

Исходная матрица:
     [,1] [,2] [,3] [,4] [,5]
[1,]   49   36    7   20   41
[2,]   37   18   36   26   25
[3,]    1   49   25   50   27
[4,]   25   47   37   47   36
[5,]   10   24   46    3   37

Элемент [3,4] = 50 

Матрица после замены 2-го столбца на 0,2,7,5,7:
     [,1] [,2] [,3] [,4] [,5]
[1,]   49    0    7   20   41
[2,]   37    2   36   26   25
[3,]    1    7   25   50   27
[4,]   25    5   37   47   36
[5,]   10    7   46    3   37

Суммы по строкам:
[1] 117 126 110 150 103

Суммы по столбцам:
[1] 122  21 151 146 166


## Потерянные списки (1 балл)

В классе учатся `n` школьников. Известно, что некоторые из них участвовали в олимпиадах:
* `a` школьников участвовали в олимпиаде по математике
* `b` школьников - по информатике
* `c` школьников - по информатике

Однако, преподаватель потерял списки участников по каждому из предметов. Помогите учителю определить, сколько школьников могло не участвовать ни в какой олимпиаде. Выведите наибольшее и наименьшее возможное число таких.

Пример ввода:
```
10
7
5
3
```

Пример вывода:
```
0
3
```

In [ ]:
n <- as.integer(readline())
a <- as.integer(readline())
b <- as.integer(readline())
c <- as.integer(readline())

max_non_part <- n - max(a, b, c)
max_non_part <- max(0, max_non_part)

min_non_part <- n - (a + b + c)
min_non_part <- max(0, min_non_part)

cat(min_non_part, "\n")
cat(max_non_part, "\n")

10
7
5
3
0 
3 


## Сложные узоры (2 балла)

Создайте матрицу 10×10 из случайных чисел.
Замените все элементы, стоящие ниже главной диагонали, на 0.
Затем замените все элементы выше диагонали на среднее значение по диагонали.

In [ ]:
set.seed(123)

matrix_10x10 <- matrix(runif(100, 1, 100), 10, 10)

cat("Исходная матрица:\n")
print(round(matrix_10x10, 2))
cat("\n")

matrix_10x10[lower.tri(matrix_10x10)] <- 0

cat("После замены ниже диагонали на 0:\n")
print(round(matrix_10x10, 2))
cat("\n")

mean_diag <- mean(diag(matrix_10x10))
matrix_10x10[upper.tri(matrix_10x10)] <- mean_diag

cat("Среднее по диагонали:", round(mean_diag, 2), "\n")
cat("Итоговая матрица:\n")
print(round(matrix_10x10, 2))

Исходная матрица:
       [,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9] [,10]
 [1,] 29.47 95.73 89.06 96.34 15.14  5.54 66.85 75.69 25.12 13.94
 [2,] 79.04 45.88 69.59 90.33 42.04 44.78 10.39 63.29 67.14 65.66
 [3,] 41.49 68.08 64.41 69.38 41.96 80.09 39.01 71.31 42.35 35.01
 [4,] 88.42 57.69 99.43 79.75 37.52 13.07 28.16  1.06 79.03 66.02
 [5,] 94.11 11.19 65.91  3.44 16.09 56.53 81.65 48.06 11.18 32.72
 [6,]  5.51 90.08 71.14 48.30 14.74 21.45 45.40 22.79 44.05 19.58
 [7,] 53.28 25.36 54.86 76.09 24.07 13.63 81.20 38.60 98.51 78.45
 [8,] 89.35  5.16 59.82 22.42 47.13 75.58 81.43 61.66 89.41 10.27
 [9,] 55.59 33.46 29.63 32.50 27.33 89.61 79.64 35.83 88.76 47.21
[10,] 46.20 95.50 15.56 23.93 85.92 38.07 44.54 12.00 18.33 51.64

После замены ниже диагонали на 0:
       [,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9] [,10]
 [1,] 29.47 95.73 89.06 96.34 15.14  5.54 66.85 75.69 25.12 13.94
 [2,]  0.00 45.88 69.59 90.33 42.04 44.78 10.39 63.29 67.14 65.66
 [3,]  0.00  0.00 64.41

## Магическое число (2 балла)

Согласно определению предела последовательности
$$
A = \lim\limits_{n\to\infty} x_n :=
\forall\varepsilon > 0 ~~ \exists N \in\mathbb{N} : \forall n > N ~~ |x_n - A| < \varepsilon
$$

Петя решил найти этот номер `N` для некоторых $\varepsilon$. Для последовательности
$$
y_n = \frac{n+5}{n+2} \arccos{\sqrt{\frac{2+(-1)^n}{4}}}
$$

при $\varepsilon = 0.01$, $\varepsilon = 0.001$ найти такие номера `N`, начиная с которых становится верным неравенство $|x_n - A| < \varepsilon$.

Для тех, чей номер ИСУ заканчивается четной цифрой, использовать $A = \frac{\pi}{3}$ и последовательность $x_n = y_{2n}$

Для тех, чей номер ИСУ заканчивается нечетной цифрой, использовать $A = \frac{\pi}{6}$ и последовательность $x_n = y_{2n-1}$


При решениии можете использовать векторные вычисления или цикл `for`.


epsilon = 0.01  => N = 77 
epsilon = 0.001  => N = 784 


## Строим зиккурат! (2 балла)

Напишите функцию, которая принимает одно целое число `n`, и возвращает пронумерованные этажи зиккурата. Представим, что мы смотрим на зиккурат сверху вниз. Этажи зиккурата нумеруются с первого, ширина каждой ступеньки равна одной строке или столбцу.

Пример ввода:
```
4
```

Пример вывода:
```
1  1  1  1  1  1  1
1  2  2  2  2  2  1
1  2  3  3  3  2  1
1  2  3  4  3  2  1
1  2  3  3  3  2  1
1  2  2  2  2  2  1
1  1  1  1  1  1  1
```

In [ ]:
ziggurat <- function(n) {
  size <- 2 * n - 1

  result <- matrix(0, nrow = size, ncol = size)
  for (i in 1:size) {
    for (j in 1:size) {
      row_dist <- min(i, size - i + 1)
      col_dist <- min(j, size - j + 1)
      result[i, j] <- min(row_dist, col_dist)
    }
  }

  output <- ""
  for (i in 1:size) {
    for (j in 1:size) {
      output <- paste0(output, result[i, j])
      if (j < size) {
        output <- paste0(output, "  ")
      }
    }
    if (i < size) {
      output <- paste0(output, "\n")
    }
  }

  return(output)
}

n <- as.integer(readline(prompt = "Введите число n: "))
cat(ziggurat(n))

Введите число n: 2
1  1  1
1  2  1
1  1  1

## Пишем Counter на R (2 балла)

В питоне есть структура `Counter`, которая на заданном наборе данных создает словарь, в котором по каждому элементу хранит информацию о том сколько данное числов встретилось в наборе.

Вам необходимо реализовать похожу функцию, но без создания структуры. Пусть дан целочисленный вектор `x`. Вам необходимо вывести информацию о том, какой элемент сколько раз встретился в этом векторе. Элементы должны быть упорядочены по возрастанию.

Так, для вектора
```R
x <- c(5, 2, 7, 7, 7, 2, 0, 0)
```

вам нужно вывести

Пример вывода:
```
0 2 5 7
2 2 1 3
```

In [ ]:
# ваш код здесь